name: SimpleDialogue
version: ${version}
main: com.lazarbow.simpledialogue.SimpleDialoguePlugin
api-version: "26.1.2"
softdepend:
  - FancyNpcs
commands:
  simpledialogue:
    description: Manage SimpleDialogue conversations.
    usage: /simpledialogue
    aliases:
      - sd
permissions:
  simpledialogue.admin:
    description: Allows editing and reloading dialogue files.
    default: op
